// Original, plain-language U.S. action guide. Review source links periodically;
// eligibility, coverage, and public-health recommendations can change.

export const categories = [
  { id: 'safety', en: { name: 'Stay safe', description: 'The few steps that matter most when something goes wrong.' }, es: { name: 'Mantente a salvo', description: 'Pasos importantes cuando algo sale mal.' } },
  { id: 'health', en: { name: 'Care for your health', description: 'Small routines and preventive care that fit real life.' }, es: { name: 'Cuida tu salud', description: 'Hábitos sencillos y atención preventiva para la vida real.' } },
  { id: 'money', en: { name: 'Make money steadier', description: 'Know what is due, protect what you have, and ask early.' }, es: { name: 'Organiza tu dinero', description: 'Ten claras tus cuentas, protege lo que tienes y pide ayuda a tiempo.' } },
  { id: 'support', en: { name: 'Find help', description: 'U.S. services for food, housing, care, and hard times.' }, es: { name: 'Encuentra apoyo', description: 'Recursos en EE. UU. para alimentos, vivienda, salud y momentos difíciles.' } },
  { id: 'home', en: { name: 'Prepare your home', description: 'Make the place you live safer and ready for disruption.' }, es: { name: 'Prepara tu hogar', description: 'Haz más seguro tu hogar y prepárate para imprevistos.' } },
  { id: 'work', en: { name: 'Protect your work life', description: 'Practical steps for pay, safety, leave, and a job search.' }, es: { name: 'Protege tu vida laboral', description: 'Pasos prácticos sobre salario, seguridad, licencias y empleo.' } },
  { id: 'connection', en: { name: 'Stay connected', description: 'Build the people and community you can count on.' }, es: { name: 'Mantén tus vínculos', description: 'Fortalece las personas y comunidades con quienes puedes contar.' } },
  { id: 'family', en: { name: 'Care for family', description: 'Support children, older adults, and the people who care for them.' }, es: { name: 'Cuida a tu familia', description: 'Apoya a niños, adultos mayores y a quienes los cuidan.' } },
  { id: 'digital', en: { name: 'Stay safer online', description: 'Protect accounts and personal information in everyday digital life.' }, es: { name: 'Protégete en línea', description: 'Cuida tus cuentas y datos personales en la vida digital.' } },
  { id: 'rights', en: { name: 'Know your options', description: 'Find a next step when a service, purchase, or legal issue goes wrong.' }, es: { name: 'Conoce tus opciones', description: 'Busca un siguiente paso si hay problemas con servicios, compras o asuntos legales.' } },
];

export const sources = [
  { id: '911', name: '911.gov: Calling 911', url: 'https://www.911.gov/calling-911/frequently-asked-questions/' },
  { id: '988', name: '988 Suicide & Crisis Lifeline', esName: 'Línea 988 de Prevención del Suicidio y Crisis', url: 'https://988lifeline.org/get-help/', esUrl: 'https://988lifeline.org/es/inicio/' },
  { id: 'belts', name: 'NHTSA: Seat belt safety', url: 'https://www.nhtsa.gov/vehicle-safety/seat-belts' },
  { id: 'carseats', name: 'NHTSA: Car seats and booster seats', url: 'https://www.nhtsa.gov/vehicle-safety/car-seats-and-booster-seats' },
  { id: 'overdose', name: 'CDC: Responding to an overdose', url: 'https://www.cdc.gov/stop-overdose/response/index.html' },
  { id: 'poison', name: 'America’s Poison Centers: Poison first aid', url: 'https://www.poisonhelp.org/first-aid/' },
  { id: 'hotline', name: 'National Domestic Violence Hotline', esName: 'Línea Nacional contra la Violencia Doméstica', url: 'https://www.thehotline.org/get-help/', esUrl: 'https://espanol.thehotline.org/' },
  { id: 'activity', name: 'HHS: Physical Activity Guidelines', url: 'https://odphp.health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines/about-physical-activity-guidelines/questions-answers' },
  { id: 'sleep', name: 'CDC: About sleep', url: 'https://www.cdc.gov/sleep/about/index.html' },
  { id: 'budgetfood', name: 'CDC: Eating healthy on a budget', esName: 'CDC: Coma sano con un presupuesto limitado', url: 'https://www.cdc.gov/diabetes/healthy-eating/6-tips-eating-healthy-on-budget.html', esUrl: 'https://www.cdc.gov/diabetes/es/healthy-eating/presupuesto-de-alimentacion-saludable.html' },
  { id: 'water', name: 'CDC: Rethink your drink', esName: 'CDC: Reconsidere lo que bebe', url: 'https://www.cdc.gov/healthy-weight-growth/rethink-your-drink/', esUrl: 'https://www.cdc.gov/healthy-weight-growth/es/rethink-your-drink/reconsidere-lo-que-bebe.html' },
  { id: 'bp', name: 'CDC: Measuring your blood pressure', url: 'https://www.cdc.gov/high-blood-pressure/measure/index.html' },
  { id: 'screening', name: 'HHS MyHealthfinder: Get screened', url: 'https://odphp.health.gov/myhealthfinder/doctor-visits/screening-tests/get-screened' },
  { id: 'vaccines', name: 'CDC: Vaccines recommended for adults', url: 'https://www.cdc.gov/vaccines-adults/recommended-vaccines/index.html' },
  { id: 'quit', name: 'CDC: Free tobacco quitline support', url: 'https://www.cdc.gov/tobacco/hcp/patient-care/quitlines-and-other-resources.html' },
  { id: 'bills', name: 'CFPB: Bill calendar', url: 'https://www.consumerfinance.gov/archive/blog/budget-help-manage-your-monthly-expenses-bill-calendar/' },
  { id: 'priority', name: 'CFPB: Prioritizing bills', url: 'https://files.consumerfinance.gov/f/documents/cfpb_your-money-your-goals_prioritizing-bills_tool.pdf' },
  { id: 'credithelp', name: 'CFPB: When you cannot pay a credit card bill', url: 'https://www.consumerfinance.gov/ask-cfpb/what-should-i-do-if-i-cant-pay-my-credit-card-bills-en-1697/' },
  { id: 'savings', name: 'CFPB: Building an emergency fund', url: 'https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/' },
  { id: 'creditreport', name: 'CFPB: Free credit reports', url: 'https://www.consumerfinance.gov/ask-cfpb/how-do-i-get-a-free-copy-of-my-credit-reports-en-5/' },
  { id: 'freeze', name: 'FTC: Credit freezes and fraud alerts', url: 'https://consumer.ftc.gov/articles/credit-freezes-and-fraud-alerts' },
  { id: 'scams', name: 'FTC: Signs of a scam', url: 'https://consumer.ftc.gov/consumer-alerts/2025/03/what-are-signs-scam' },
  { id: 'bankfees', name: 'CFPB: Compare checking account fees', url: 'https://www.consumerfinance.gov/ask-cfpb/should-i-get-a-checking-account-that-pays-interest-en-925/' },
  { id: '211', name: 'United Way 211: Local help', url: 'https://211.org/' },
  { id: 'snap', name: 'USDA: SNAP state directory', url: 'https://www.fna.usda.gov/snap/state-directory' },
  { id: 'hrsa', name: 'HRSA: Find a health center', url: 'https://findahealthcenter.hrsa.gov/' },
  { id: 'hrsaeligibility', name: 'HRSA: Health center cost and eligibility', url: 'https://www.hrsa.gov/get-health-care/affordable/eligibility' },
  { id: 'coverage', name: 'HealthCare.gov: Get coverage', esName: 'CuidadoDeSalud.gov: Obtenga cobertura', url: 'https://www.healthcare.gov/get-coverage/', esUrl: 'https://www.cuidadodesalud.gov/es/get-coverage/' },
  { id: 'prevention', name: 'HealthCare.gov: Preventive care benefits', url: 'https://www.healthcare.gov/coverage/preventive-care-benefits/' },
  { id: 'treatment', name: 'SAMHSA: Treatment locators', url: 'https://www.samhsa.gov/find-help/locators' },
  { id: 'rent', name: 'USAGov: Emergency rent assistance', url: 'https://www.usa.gov/emergency-pay-rent' },
  { id: 'unemployment', name: 'USAGov: Unemployment benefits', url: 'https://www.usa.gov/unemployment-benefits' },
  { id: 'smoke', name: 'U.S. Fire Administration: Smoke alarms', url: 'https://www.usfa.fema.gov/prevention/home-fires/prepare-for-fire/smoke-alarms/' },
  { id: 'co', name: 'U.S. Fire Administration: Carbon monoxide safety', url: 'https://www.usfa.fema.gov/prevention/life-safety-hazards/carbon-monoxide/index.html' },
  { id: 'generator', name: 'CDC: Power outage and generator safety', url: 'https://www.cdc.gov/natural-disasters/response/what-to-do-protect-yourself-during-a-power-outage.html' },
  { id: 'ready', name: 'FEMA Ready.gov: Disaster planning', url: 'https://www.ready.gov/' },
  { id: 'escape', name: 'U.S. Fire Administration: Home fire escape plans', url: 'https://www.usfa.fema.gov/prevention/home-fires/prepare-for-fire/home-fire-escape-plans/' },
  { id: 'radon', name: 'EPA: Radon in homes', url: 'https://www.epa.gov/radtown/radon-homes-schools-and-buildings' },
  { id: 'wages', name: 'U.S. Department of Labor: Wage complaint', url: 'https://www.dol.gov/agencies/whd/contact/complaints' },
  { id: 'osha', name: 'OSHA: File a workplace safety complaint', url: 'https://www.osha.gov/workers/file-complaint' },
  { id: 'jobcenter', name: 'U.S. Department of Labor: American Job Centers', url: 'https://cloudfront.careeronestop.org/LocalHelp/AmericanJobCenters/american-job-centers.aspx' },
  { id: 'fmla', name: 'U.S. Department of Labor: Family and Medical Leave Act', url: 'https://www.dol.gov/agencies/whd/fact-sheets/28-fmla' },
  { id: 'jobscams', name: 'FTC: Job scams', url: 'https://consumer.ftc.gov/articles/job-scams' },
  { id: 'fatigue', name: 'CDC NIOSH: Fatigue and work', url: 'https://www.cdc.gov/niosh/fatigue/about/index.html' },
  { id: 'connection', name: 'CDC: Improving social connectedness', url: 'https://www.cdc.gov/social-connectedness/improving/index.html' },
];

export const actions = [
  {
    id: 'emergency-call', category: 'safety', effort: 'today',
    en: { title: 'Know when to call 911', why: 'Emergency responders can act when someone faces immediate danger.', step: 'For a life-threatening medical emergency, fire, or immediate threat, call 911 and say where you are.' },
    es: { title: 'Ten claro cuándo llamar al 911', why: 'Los servicios de emergencia pueden actuar cuando hay peligro inmediato.', step: 'Ante una emergencia médica grave, un incendio o una amenaza inmediata, llama al 911 y di dónde estás.' },
    sources: ['911'],
  },
  {
    id: 'crisis-988', category: 'safety', effort: 'today',
    en: { title: 'Save 988 for a hard moment', why: 'You can reach a crisis counselor for emotional distress, even if you are not thinking about suicide.', step: 'Call or text 988. For Spanish, call 988 and press 2, or text AYUDA to 988. If someone is in immediate physical danger, call 911.' },
    es: { title: 'Guarda el 988 para un momento difícil', why: 'Puedes hablar con alguien capacitado en crisis emocionales, aunque no estés pensando en suicidarte.', step: 'Llama al 988 y presiona 2, o envía AYUDA por texto al 988. Si hay peligro físico inmediato, llama al 911.' },
    sources: ['988'],
  },
  {
    id: 'belt-every-seat', category: 'safety', effort: 'today',
    en: { title: 'Buckle up in every seat', why: 'A short trip or back seat still calls for a seat belt.', step: 'Before the car moves, check that every passenger is buckled, including in a taxi or rideshare.' },
    es: { title: 'Usa el cinturón en cualquier asiento', why: 'También hace falta en trayectos cortos y en el asiento trasero.', step: 'Antes de arrancar, comprueba que todas las personas lleven cinturón, incluso en taxis y viajes por aplicación.' },
    sources: ['belts'],
  },
  {
    id: 'child-car-seat', category: 'safety', effort: 'week',
    en: { title: 'Check a child’s car seat', why: 'The right restraint depends on the child’s size and the seat’s limits.', step: 'Read the seat and vehicle instructions; use NHTSA’s guide and look for a free inspection if you are unsure.' },
    es: { title: 'Revisa la silla infantil del auto', why: 'El sistema adecuado depende del tamaño del niño y de los límites de la silla.', step: 'Lee las instrucciones de la silla y del vehículo; consulta la guía de NHTSA y busca una revisión gratuita si tienes dudas.' },
    sources: ['carseats'],
  },
  {
    id: 'overdose-response', category: 'safety', effort: 'plan',
    en: { title: 'Prepare for an opioid overdose', why: 'Naloxone can reverse an opioid overdose while emergency help is on the way.', step: 'If someone may be at risk, learn where to get naloxone. If you suspect an overdose, give it if available and call 911.' },
    es: { title: 'Prepárate ante una sobredosis de opioides', why: 'La naloxona puede revertir una sobredosis mientras llega la ayuda.', step: 'Si alguien podría estar en riesgo, averigua dónde conseguir naloxona. Si sospechas una sobredosis, adminístrala si la tienes y llama al 911.' },
    sources: ['overdose'],
  },
  {
    id: 'poison-help', category: 'safety', effort: 'today',
    en: { title: 'Save Poison Help', why: 'A poison specialist can guide you before symptoms appear.', step: 'Save 1-800-222-1222. If someone collapses, has a seizure, cannot breathe, or cannot be awakened, call 911.' },
    es: { title: 'Guarda el número de Poison Help', why: 'Un especialista puede orientarte antes de que aparezcan síntomas.', step: 'Guarda el 1-800-222-1222. Si alguien se desmaya, convulsiona, no puede respirar o no despierta, llama al 911.' },
    sources: ['poison'],
  },
  {
    id: 'relationship-safety', category: 'safety', effort: 'today',
    en: { title: 'Get private help with relationship abuse', why: 'A trained advocate can help you think through safer options.', step: 'Call 1-800-799-7233 or text START to 88788 when it is safe to do so. If you face immediate danger, call 911.' },
    es: { title: 'Busca apoyo privado ante el abuso de pareja', why: 'Una persona capacitada puede ayudarte a pensar en opciones más seguras.', step: 'Cuando sea seguro, llama al 1-800-799-7233 o envía START al 88788. Si hay peligro inmediato, llama al 911.' },
    sources: ['hotline'],
  },

  {
    id: 'move-more', category: 'health', effort: 'today',
    en: { title: 'Start with movement you can do', why: 'Some activity is better than none; the goal can grow with you.', step: 'Walk, roll, dance, or do another accessible activity for a few minutes. Build toward 150 minutes of moderate activity a week and strength work twice a week.' },
    es: { title: 'Empieza con un movimiento que puedas hacer', why: 'Algo de actividad es mejor que nada; puedes aumentar poco a poco.', step: 'Camina, muévete en silla de ruedas, baila o haz otra actividad accesible unos minutos. Avanza hacia 150 minutos semanales de actividad moderada y haz ejercicios de fuerza dos días.' },
    sources: ['activity'],
  },
  {
    id: 'sleep-window', category: 'health', effort: 'today',
    en: { title: 'Protect a regular sleep window', why: 'Most adults need at least seven hours of sleep.', step: 'Choose a wake time you can usually keep, then leave enough time for sleep. Ask a clinician if poor sleep persists.' },
    es: { title: 'Reserva un horario regular para dormir', why: 'La mayoría de las personas adultas necesita al menos siete horas.', step: 'Elige una hora de levantarte que puedas mantener y reserva tiempo suficiente para dormir. Consulta a un profesional si el problema continúa.' },
    sources: ['sleep'],
  },
  {
    id: 'budget-meal', category: 'health', effort: 'week',
    en: { title: 'Plan one affordable meal', why: 'Healthy food can include frozen, canned, and shelf-stable ingredients.', step: 'Check what you already have, then plan one meal with vegetables or fruit, a protein, and a grain you like.' },
    es: { title: 'Planea una comida que se ajuste a tu presupuesto', why: 'Comer bien también puede incluir alimentos congelados, enlatados y de despensa.', step: 'Revisa lo que ya tienes y planea una comida con verduras o fruta, una proteína y arroz, tortilla u otro grano que te guste.' },
    sources: ['budgetfood'],
  },
  {
    id: 'swap-drink', category: 'health', effort: 'today',
    en: { title: 'Swap one sugary drink', why: 'Sweetened drinks can add a lot of sugar without much nutrition.', step: 'Try water, unsweetened tea, or sparkling water for one drink you usually buy.' },
    es: { title: 'Cambia una bebida azucarada', why: 'Las bebidas endulzadas pueden añadir mucha azúcar y pocos nutrientes.', step: 'Prueba agua, té sin azúcar o agua con gas en lugar de una bebida que sueles comprar.' },
    sources: ['water'],
  },
  {
    id: 'blood-pressure', category: 'health', effort: 'week',
    en: { title: 'Know your blood pressure', why: 'High blood pressure often has no warning signs.', step: 'Get a reading at a clinic, pharmacy, or with a home monitor. Share repeated high readings with your care team.' },
    es: { title: 'Conoce tu presión arterial', why: 'La presión alta a menudo no da señales.', step: 'Mídela en una clínica, farmacia o con un aparato en casa. Comenta las lecturas altas repetidas con tu equipo médico.' },
    sources: ['bp'],
  },
  {
    id: 'screening-plan', category: 'health', effort: 'plan',
    en: { title: 'Make a personal screening plan', why: 'Useful tests depend on age, history, and other factors.', step: 'Use MyHealthfinder, then ask a clinician which screenings make sense for you and how to get the results.' },
    es: { title: 'Haz un plan personal de exámenes preventivos', why: 'Los estudios útiles dependen de tu edad, antecedentes y otros factores.', step: 'Consulta MyHealthfinder y pregunta a un profesional qué exámenes te corresponden y cómo recibir los resultados.' },
    sources: ['screening'],
  },
  {
    id: 'vaccine-review', category: 'health', effort: 'plan',
    en: { title: 'Review your vaccines', why: 'Recommendations change with age, health conditions, and new guidance.', step: 'Bring your vaccine record to a pharmacist or clinician and ask what is recommended for you now.' },
    es: { title: 'Revisa tus vacunas', why: 'Las recomendaciones cambian según la edad, la salud y las guías vigentes.', step: 'Lleva tu registro de vacunas a una farmacia o consulta médica y pregunta cuáles te recomiendan ahora.' },
    sources: ['vaccines'],
  },
  {
    id: 'quit-tobacco', category: 'health', effort: 'today',
    en: { title: 'Get help to quit tobacco', why: 'Free quitline coaching can make quitting more manageable.', step: 'Call 1-800-QUIT-NOW. For Spanish coaching, call 1-855-DÉJELO-YA.' },
    es: { title: 'Busca apoyo para dejar el tabaco', why: 'La orientación gratuita puede hacer más llevadero el proceso.', step: 'Llama al 1-855-DÉJELO-YA para recibir apoyo en español, o al 1-800-QUIT-NOW.' },
    sources: ['quit'],
  },

  {
    id: 'bill-calendar', category: 'money', effort: 'today',
    en: { title: 'Put every bill on one calendar', why: 'Seeing amounts and due dates together helps you plan the month.', step: 'Write each bill, amount, and due date on paper or in your phone; check the list once a week.' },
    es: { title: 'Anota todas tus cuentas en un calendario', why: 'Ver montos y fechas juntos ayuda a planear el mes.', step: 'Anota cada cuenta, su monto y fecha de pago en papel o en el teléfono; revísalas una vez por semana.' },
    sources: ['bills'],
  },
  {
    id: 'bill-priority', category: 'money', effort: 'today',
    en: { title: 'If money is short, rank the bills', why: 'Different missed payments have different consequences.', step: 'List what is due and the effect of paying late. Protect essentials such as housing, utilities, food, and what you need to earn income.' },
    es: { title: 'Si no alcanza el dinero, ordena las cuentas', why: 'Cada pago atrasado tiene consecuencias distintas.', step: 'Anota lo que debes y qué pasaría si pagas tarde. Da prioridad a vivienda, servicios, comida y lo necesario para trabajar.' },
    sources: ['priority'],
  },
  {
    id: 'call-creditor', category: 'money', effort: 'today',
    en: { title: 'Call before a credit card payment is missed', why: 'The card company may discuss a payment change if you are in trouble.', step: 'Explain what happened, what you can afford, and when you could resume normal payments; ask for the agreement in writing.' },
    es: { title: 'Llama antes de atrasarte con la tarjeta', why: 'La compañía puede considerar cambios en el pago si tienes dificultades.', step: 'Explica qué pasó, cuánto puedes pagar y cuándo podrías volver al pago normal; pide el acuerdo por escrito.' },
    sources: ['credithelp'],
  },
  {
    id: 'starter-savings', category: 'money', effort: 'week',
    en: { title: 'Start an emergency fund at any size', why: 'Even a small reserve can help with an unexpected bill.', step: 'Choose a safe, accessible place for savings and set aside an amount that fits your situation when you can.' },
    es: { title: 'Empieza un fondo para imprevistos', why: 'Incluso una pequeña reserva puede ayudar con un gasto inesperado.', step: 'Elige un lugar seguro y accesible para guardarla y aparta lo que puedas cuando te sea posible.' },
    sources: ['savings'],
  },
  {
    id: 'credit-report', category: 'money', effort: 'plan',
    en: { title: 'Check your credit reports for errors', why: 'A report can reveal accounts or details you do not recognize.', step: 'Use the official AnnualCreditReport.com link from the CFPB and review each report.' },
    es: { title: 'Revisa tus informes de crédito', why: 'Podrías encontrar cuentas o datos que no reconoces.', step: 'Entra a AnnualCreditReport.com desde el enlace oficial de CFPB y revisa cada informe.' },
    sources: ['creditreport'],
  },
  {
    id: 'credit-freeze', category: 'money', effort: 'plan',
    en: { title: 'Consider a free credit freeze', why: 'It can make it harder for someone else to open new credit in your name.', step: 'If it fits your situation, contact all three credit bureaus. You can lift the freeze when you need to apply for credit.' },
    es: { title: 'Considera congelar tu crédito gratis', why: 'Puede dificultar que otra persona abra crédito a tu nombre.', step: 'Si te conviene, comunícate con las tres agencias de crédito. Podrás levantar el bloqueo cuando necesites solicitar crédito.' },
    sources: ['freeze'],
  },
  {
    id: 'verify-request', category: 'money', effort: 'today',
    en: { title: 'Verify a surprise request for money', why: 'Scammers create urgency and impersonate people or agencies.', step: 'Pause. Contact the person or organization using a number or website you found yourself, never the one in the message.' },
    es: { title: 'Verifica cualquier pedido inesperado de dinero', why: 'Los estafadores meten prisa y se hacen pasar por personas o entidades conocidas.', step: 'Haz una pausa. Contacta a la persona o entidad con un número o sitio que hayas buscado tú, no con el del mensaje.' },
    sources: ['scams'],
  },
  {
    id: 'bank-fees', category: 'money', effort: 'week',
    en: { title: 'Check what your bank account costs', why: 'Monthly and transaction fees can eat into money you need.', step: 'Read your account fee schedule and compare it with another bank or credit union account that fits how you use it.' },
    es: { title: 'Revisa cuánto te cuesta tu cuenta bancaria', why: 'Las cuotas mensuales y por transacción pueden reducir tu dinero disponible.', step: 'Lee la lista de cargos y compárala con otra cuenta bancaria o de cooperativa de crédito que se ajuste a tu uso.' },
    sources: ['bankfees'],
  },

  {
    id: 'call-211', category: 'support', effort: 'today',
    en: { title: 'Use 211 to find local help', why: 'A local specialist can point you toward food, housing, utility, and other services.', step: 'Call 211 or search your local 211 site. Ask what is available where you live.' },
    es: { title: 'Llama al 211 para encontrar ayuda local', why: 'Una persona de tu zona puede orientarte sobre alimentos, vivienda, servicios y más.', step: 'Llama al 211 o consulta el sitio local de 211. Pregunta qué recursos hay donde vives.' },
    sources: ['211'],
  },
  {
    id: 'snap-check', category: 'support', effort: 'week',
    en: { title: 'Check food benefit options', why: 'SNAP may help eligible households buy food; rules and applications vary by state.', step: 'Use USDA’s state directory to reach your state SNAP office and check current eligibility.' },
    es: { title: 'Consulta la ayuda para comprar alimentos', why: 'SNAP puede ayudar a hogares que cumplan los requisitos; las reglas cambian según el estado.', step: 'Usa el directorio de USDA para contactar a la oficina de SNAP de tu estado y revisar los requisitos actuales.' },
    sources: ['snap'],
  },
  {
    id: 'health-center', category: 'support', effort: 'week',
    en: { title: 'Find care even without insurance', why: 'Community health centers serve people with or without insurance and adjust charges by income.', step: 'Search by ZIP code on HRSA’s health-center finder; call the center to ask about costs and appointments.' },
    es: { title: 'Busca atención médica aunque no tengas seguro', why: 'Los centros de salud comunitarios atienden con o sin seguro y ajustan los costos según los ingresos.', step: 'Busca por código postal en el localizador de HRSA; llama al centro para preguntar por costos y citas.' },
    sources: ['hrsa', 'hrsaeligibility'],
  },
  {
    id: 'health-coverage', category: 'support', effort: 'plan',
    en: { title: 'Check health coverage options', why: 'Marketplace and public coverage options depend on your household and where you live.', step: 'Start at HealthCare.gov, or its Spanish site, to see your current options and enrollment steps.' },
    es: { title: 'Consulta tus opciones de seguro médico', why: 'Las opciones del Mercado y de cobertura pública dependen de tu hogar y del lugar donde vives.', step: 'Empieza en CuidadoDeSalud.gov para ver tus opciones y los pasos de inscripción vigentes.' },
    sources: ['coverage'],
  },
  {
    id: 'treatment-search', category: 'support', effort: 'today',
    en: { title: 'Find mental health or substance use care', why: 'You do not have to find a provider by word of mouth alone.', step: 'Search SAMHSA’s FindTreatment.gov by location; for an immediate emotional crisis, call or text 988.' },
    es: { title: 'Busca atención de salud mental o por consumo de sustancias', why: 'No tienes que encontrar ayuda solo por recomendaciones personales.', step: 'Busca por zona en FindTreatment.gov de SAMHSA; si hay una crisis emocional inmediata, llama al 988 y oprime 2, o envía AYUDA al 988.' },
    sources: ['treatment', '988'],
  },
  {
    id: 'rent-help', category: 'support', effort: 'today',
    en: { title: 'Ask for rent help early', why: 'Programs and eligibility vary by state and locality.', step: 'Call 211 or use USAGov’s rent-help page to find current local programs. Contact your landlord about options too.' },
    es: { title: 'Pide ayuda con el alquiler a tiempo', why: 'Los programas y requisitos varían según el estado y la localidad.', step: 'Llama al 211 o usa la página de USAGov para encontrar programas locales vigentes. Pregunta también al propietario o arrendador por posibles opciones.' },
    sources: ['rent', '211'],
  },
  {
    id: 'unemployment-check', category: 'support', effort: 'today',
    en: { title: 'Check unemployment benefits after job loss', why: 'Each state runs its own program and sets its own rules.', step: 'Use USAGov’s state finder to learn where and how to apply; keep records of your work and separation.' },
    es: { title: 'Consulta el seguro de desempleo si pierdes tu empleo', why: 'Cada estado administra su programa y fija sus reglas.', step: 'Usa el buscador por estado de USAGov para saber dónde solicitarlo; conserva tus documentos de trabajo y salida.' },
    sources: ['unemployment'],
  },

  {
    id: 'test-smoke', category: 'home', effort: 'today',
    en: { title: 'Test your smoke alarms', why: 'An alarm only helps if it works and you can hear it.', step: 'Press the test button monthly. Check for alarms inside each bedroom, outside sleeping areas, and on every level. Ask a landlord if installation is needed.' },
    es: { title: 'Prueba las alarmas de humo', why: 'Solo ayudan si funcionan y puedes oírlas.', step: 'Oprime el botón de prueba cada mes. Revisa que haya alarmas dentro de cada dormitorio, fuera de las zonas para dormir y en cada piso. Pide la instalación al propietario si hace falta.' },
    sources: ['smoke'],
  },
  {
    id: 'co-alarm', category: 'home', effort: 'week',
    en: { title: 'Check carbon monoxide alarms', why: 'Carbon monoxide cannot be seen or smelled.', step: 'Install and maintain CO alarms according to the maker’s directions, especially near sleeping areas.' },
    es: { title: 'Revisa las alarmas de monóxido de carbono', why: 'El monóxido de carbono no se ve ni se huele.', step: 'Instala y mantén las alarmas siguiendo las instrucciones del fabricante, sobre todo cerca de donde se duerme.' },
    sources: ['co'],
  },
  {
    id: 'generator-outside', category: 'home', effort: 'plan',
    en: { title: 'Keep generators outside', why: 'Engine exhaust can cause deadly carbon monoxide poisoning.', step: 'Never run a generator inside a home or garage, even with doors open; keep it at least 20 feet from windows, doors, and vents.' },
    es: { title: 'Usa los generadores solo afuera', why: 'Sus gases pueden causar una intoxicación mortal por monóxido de carbono.', step: 'Nunca enciendas un generador dentro de la casa o el garaje, aunque las puertas estén abiertas; déjalo a por lo menos 20 pies de ventanas, puertas y ventilas.' },
    sources: ['generator'],
  },
  {
    id: 'fire-exit', category: 'home', effort: 'week',
    en: { title: 'Choose two ways out', why: 'In a home fire, there may be very little time to leave.', step: 'Find two exits from each room if possible, agree on a meeting place outside, and practice leaving.' },
    es: { title: 'Elige dos salidas', why: 'En un incendio en casa puede haber muy poco tiempo para salir.', step: 'Identifica dos salidas de cada cuarto si es posible, acuerda un lugar de reunión afuera y practica la salida.' },
    sources: ['escape'],
  },
  {
    id: 'local-alerts', category: 'home', effort: 'week',
    en: { title: 'Turn on local emergency alerts', why: 'Flood, fire, heat, storm, and other risks differ by location.', step: 'Keep wireless emergency alerts on and learn how your local officials send evacuation information.' },
    es: { title: 'Activa las alertas de emergencia locales', why: 'Los riesgos de inundación, incendio, calor o tormenta cambian según la zona.', step: 'Mantén activas las alertas inalámbricas y averigua cómo informa tu localidad sobre evacuaciones.' },
    sources: ['ready'],
  },
  {
    id: 'contact-plan', category: 'home', effort: 'week',
    en: { title: 'Make a household contact plan', why: 'People may be apart when a disaster happens.', step: 'Choose a meeting place and an out-of-area contact; include children, pets, and any accessibility or medical needs.' },
    es: { title: 'Haz un plan de contacto para tu hogar', why: 'La familia puede estar separada cuando ocurre una emergencia.', step: 'Elige un punto de encuentro y un contacto fuera de la zona; incluye a niños, mascotas y necesidades médicas o de accesibilidad.' },
    sources: ['ready'],
  },
  {
    id: 'basic-kit', category: 'home', effort: 'plan',
    en: { title: 'Build a small emergency kit', why: 'An outage or evacuation is easier to handle when basics are ready.', step: 'Start with water, food, medicines, a flashlight, chargers, and copies of essential information; add what your household needs.' },
    es: { title: 'Arma un kit básico de emergencia', why: 'Es más fácil enfrentar un apagón o una evacuación si tienes lo esencial listo.', step: 'Empieza con agua, comida, medicamentos, linterna, cargadores y copias de datos importantes; añade lo que necesite tu hogar.' },
    sources: ['ready'],
  },
  {
    id: 'radon-test', category: 'home', effort: 'plan',
    en: { title: 'Test your home for radon', why: 'Radon has no smell, and levels can be high in any state.', step: 'Use an EPA-guided home test or ask a qualified professional; follow EPA advice if the result is elevated.' },
    es: { title: 'Haz una prueba de radón en casa', why: 'El radón no tiene olor y puede estar elevado en cualquier estado.', step: 'Usa una prueba casera según la guía de EPA o consulta a un profesional calificado; sigue las recomendaciones si el resultado es alto.' },
    sources: ['radon'],
  },

  {
    id: 'pay-records', category: 'work', effort: 'today',
    en: { title: 'Keep your own record of hours and pay', why: 'Clear records help when a paycheck or schedule is disputed.', step: 'Save pay stubs and note shifts, hours, and messages about pay in a place you control.' },
    es: { title: 'Lleva tu propio registro de horas y pagos', why: 'Los documentos claros ayudan si hay desacuerdos sobre el salario o el horario.', step: 'Guarda recibos de pago y anota turnos, horas y mensajes sobre el sueldo en un lugar al que tengas acceso.' },
    sources: ['wages'],
  },
  {
    id: 'unpaid-wages', category: 'work', effort: 'today',
    en: { title: 'Ask about unpaid wages', why: 'The U.S. Department of Labor takes confidential wage complaints.', step: 'Gather pay stubs, hours, and employer details; call 1-866-487-9243 or use the Wage and Hour Division site.' },
    es: { title: 'Consulta si te deben salario', why: 'El Departamento de Trabajo recibe quejas salariales de forma confidencial.', step: 'Reúne recibos, horas y datos del empleador; llama al 1-866-487-9243 o consulta la División de Horas y Salarios.' },
    sources: ['wages'],
  },
  {
    id: 'unsafe-work', category: 'work', effort: 'today',
    en: { title: 'Report a serious workplace hazard', why: 'Workers can ask OSHA to review unsafe or unhealthy conditions.', step: 'Document the hazard and contact OSHA or your state plan; for imminent danger, use the emergency contact on OSHA’s page.' },
    es: { title: 'Informa sobre un peligro grave en el trabajo', why: 'Los trabajadores pueden pedir que OSHA revise condiciones inseguras o insalubres.', step: 'Documenta el peligro y contacta a OSHA o al programa de tu estado; ante peligro inminente, usa el contacto urgente indicado en su página.' },
    sources: ['osha'],
  },
  {
    id: 'job-center', category: 'work', effort: 'week',
    en: { title: 'Use a free job center', why: 'American Job Centers offer job-search help, workshops, and computer access.', step: 'Search by ZIP code for a nearby center and ask which services are available in your language.' },
    es: { title: 'Acude a un centro de empleo gratuito', why: 'Los American Job Centers ofrecen ayuda para buscar trabajo, talleres y acceso a computadoras.', step: 'Busca un centro por código postal y pregunta qué servicios hay en tu idioma.' },
    sources: ['jobcenter'],
  },
  {
    id: 'leave-options', category: 'work', effort: 'plan',
    en: { title: 'Check your family or medical leave options', why: 'Federal and state protections may apply to a health or caregiving need.', step: 'Read the Labor Department’s FMLA guide and ask your employer or state labor office about your situation.' },
    es: { title: 'Consulta tus opciones de licencia familiar o médica', why: 'Podrían existir protecciones federales o estatales por salud o cuidado de familiares.', step: 'Lee la guía del Departamento de Trabajo sobre FMLA y consulta a tu empleador o a la oficina laboral estatal.' },
    sources: ['fmla'],
  },
  {
    id: 'job-offer-scam', category: 'work', effort: 'today',
    en: { title: 'Do not pay to get a job', why: 'A request for money or a check that you must forward is a common job-scam sign.', step: 'Verify the employer through its own site; do not send money or sensitive data to a surprise recruiter.' },
    es: { title: 'No pagues para conseguir un empleo', why: 'Que te pidan dinero o reenviar parte de un cheque es una señal frecuente de estafa laboral.', step: 'Verifica al empleador en su propio sitio; no envíes dinero ni datos sensibles a un reclutador desconocido.' },
    sources: ['jobscams'],
  },
  {
    id: 'work-fatigue', category: 'work', effort: 'week',
    en: { title: 'Take work fatigue seriously', why: 'Fatigue can slow attention and judgment, especially with long or night shifts.', step: 'Notice when you are too tired for a safety-critical task or drive; discuss breaks or a safer schedule with a supervisor when possible.' },
    es: { title: 'Toma en serio el cansancio laboral', why: 'La fatiga puede afectar la atención y el juicio, sobre todo con turnos largos o nocturnos.', step: 'Reconoce si estás demasiado cansado para una tarea riesgosa o para conducir; cuando sea posible, habla sobre descansos u horarios más seguros.' },
    sources: ['fatigue'],
  },

  {
    id: 'real-check-in', category: 'connection', effort: 'today',
    en: { title: 'Check in with one person', why: 'Small, genuine contact can help build supportive ties.', step: 'Send a message that names something real: “I thought of you today. How are things?”' },
    es: { title: 'Pregunta de verdad cómo está alguien', why: 'Un contacto pequeño y sincero puede fortalecer el apoyo mutuo.', step: 'Envía un mensaje concreto: “Hoy pensé en ti. ¿Cómo te va?”' },
    sources: ['connection'],
  },
  {
    id: 'recurring-time', category: 'connection', effort: 'week',
    en: { title: 'Put connection on the calendar', why: 'Regular contact is easier to keep when it has a place in your week.', step: 'Choose a short weekly call, walk, meal, or video chat with someone you want to know better.' },
    es: { title: 'Reserva tiempo para tus vínculos', why: 'Es más fácil mantener el contacto cuando tiene un espacio en la semana.', step: 'Elige una llamada, caminata, comida o videollamada breve cada semana con alguien cercano.' },
    sources: ['connection'],
  },
  {
    id: 'join-group', category: 'connection', effort: 'plan',
    en: { title: 'Join a group around an interest', why: 'Shared activities can create a sense of belonging.', step: 'Look for a library, recreation, faith, volunteer, or neighborhood group that welcomes new people.' },
    es: { title: 'Únete a un grupo que te interese', why: 'Las actividades compartidas pueden ayudarte a sentirte parte de una comunidad.', step: 'Busca un grupo de biblioteca, recreación, fe, voluntariado o barrio que reciba a gente nueva.' },
    sources: ['connection'],
  },
  {
    id: 'share-task', category: 'connection', effort: 'week',
    en: { title: 'Share an ordinary activity', why: 'Connection does not need an expensive or formal plan.', step: 'Invite someone to cook, walk, shop, garden, or run an errand together.' },
    es: { title: 'Comparte una actividad cotidiana', why: 'Conectar con alguien no requiere gastar dinero ni hacer un gran plan.', step: 'Invita a alguien a cocinar, caminar, comprar, cuidar plantas o hacer un mandado juntos.' },
    sources: ['connection'],
  },
  {
    id: 'ask-specific-help', category: 'connection', effort: 'today',
    en: { title: 'Ask for one specific kind of help', why: 'A clear request can make it easier for someone to support you.', step: 'Try: “Could you call me tonight?” or “Could you give me a ride to this appointment?”' },
    es: { title: 'Pide una ayuda concreta', why: 'Una petición clara facilita que otra persona te apoye.', step: 'Prueba con: “¿Puedes llamarme esta noche?” o “¿Puedes llevarme a esta cita?”' },
    sources: ['connection'],
  },
  {
    id: 'offer-help', category: 'connection', effort: 'today',
    en: { title: 'Offer practical help without pressure', why: 'Support works best when it respects what the other person wants.', step: 'Ask: “Would a meal, a ride, or company help this week?” Accept their answer.' },
    es: { title: 'Ofrece ayuda práctica sin presionar', why: 'El apoyo funciona mejor cuando respeta lo que la otra persona desea.', step: 'Pregunta: “¿Te ayudaría una comida, que te lleve o que te acompañe esta semana?” Respeta su respuesta.' },
    sources: ['connection'],
  },
  {
    id: 'loneliness-support', category: 'connection', effort: 'week',
    en: { title: 'Get support if loneliness is weighing on you', why: 'Persistent disconnection can be hard to solve alone.', step: 'Tell a trusted person or health professional what has been going on; ask about groups or care nearby.' },
    es: { title: 'Busca apoyo si la soledad te está afectando', why: 'Cuando el aislamiento persiste, puede ser difícil afrontarlo a solas.', step: 'Cuéntale a alguien de confianza o a un profesional de salud lo que pasa; pregunta por grupos o atención cerca de ti.' },
    sources: ['connection', 'treatment'],
  },
];
