// Original, plain-language U.S. family and caregiving actions.
// Program rules and clinical guidance can change; review linked sources periodically.

export const sources = [
  { id: 'family-safe-sleep', name: 'CDC: Safe sleep for babies', url: 'https://www.cdc.gov/reproductive-health/features/babies-sleep.html' },
  { id: 'family-water', name: 'CDC: Preventing drowning', url: 'https://www.cdc.gov/drowning/prevention/index.html' },
  { id: 'family-medicine-storage', name: 'CDC: Medication safety at home', url: 'https://www.cdc.gov/medication-safety/php/toolkit/index.html' },
  { id: 'family-milestones', name: 'CDC: Learn the Signs. Act Early.', url: 'https://www.cdc.gov/act-early/' },
  { id: 'family-child-checkup', name: 'HHS MyHealthfinder: Child checkups', url: 'https://odphp.health.gov/myhealthfinder/doctor-visits/regular-checkups' },
  { id: 'family-teen-talk', name: 'CDC: Talk to your teen about mental health', url: 'https://www.cdc.gov/free-mind/parents/talk-to-your-teen.html' },
  { id: 'family-childcare', name: 'Childcare.gov: Child care financial assistance', url: 'https://www.childcare.gov/consumer-education/get-help-paying-for-child-care/child-care-financial-assistance-options' },
  { id: 'family-headstart', name: 'HHS: Head Start Center Locator', url: 'https://www.headstart.gov/center-locator' },
  { id: 'family-wic', name: 'USAGov: WIC food assistance', url: 'https://www.usa.gov/food-assistance' },
  { id: 'family-school-support', name: 'USAGov: Early intervention and special education services', esName: 'USAGov: Intervención temprana y educación especial', url: 'https://www.usa.gov/special-education', esUrl: 'https://www.usa.gov/es/educacion-especial' },
  { id: 'family-falls', name: 'CDC: Preventing older adult falls', url: 'https://www.cdc.gov/falls/prevention/index.html' },
  { id: 'family-older-vision', name: 'CDC: Vision health and falls', url: 'https://www.cdc.gov/vision-health/prevention/older-adult-falls.html' },
  { id: 'family-medicine-review', name: 'NIA: Taking medicines safely as you age', url: 'https://www.nia.nih.gov/health/medicines-and-medication-management/taking-medicines-safely-you-age' },
  { id: 'family-driving', name: 'CDC: Older adult drivers', url: 'https://www.cdc.gov/older-adult-drivers/about/index.html' },
  { id: 'family-care-wishes', name: 'NIA: Advance care planning', url: 'https://www.nia.nih.gov/health/advance-care-planning/advance-care-planning-advance-directives-health-care' },
  { id: 'family-care-notebook', name: 'NIA: Caregiver worksheets', url: 'https://www.nia.nih.gov/health/caregiving/caregiver-worksheets' },
  { id: 'family-care-team', name: 'NIA: Sharing caregiving responsibilities', url: 'https://www.nia.nih.gov/health/caregiving/sharing-caregiving-responsibilities' },
  { id: 'family-respite', name: 'NIA: What is respite care?', url: 'https://www.nia.nih.gov/health/caregiving/what-respite-care' },
  { id: 'family-eldercare', name: 'Administration for Community Living: Eldercare Locator', esName: 'USAGov: Administración para la Vida Comunitaria', url: 'https://eldercare.acl.gov/', esUrl: 'https://www.usa.gov/es/agencias/administracion-para-la-vida-comunitaria' },
  { id: 'family-caregiver-health', name: 'NIA: Taking care of yourself as a caregiver', url: 'https://www.nia.nih.gov/health/caregiving/take-care-yourself-caregiver' },
  { id: 'family-communication', name: 'U.S. Department of Justice: ADA effective communication', url: 'https://www.ada.gov/resources/effective-communication/' },
  { id: 'family-transit', name: 'Federal Transit Administration: ADA paratransit questions', url: 'https://www.transit.dot.gov/regulations-and-guidance/civil-rights-ada/frequently-asked-questions' },
  { id: 'family-disability-ready', name: 'FEMA Ready.gov: Emergency planning with a disability', url: 'https://www.ready.gov/sites/default/files/2023-05/ready.gov_disabilities_bookmark_front-back.pdf' },
  { id: 'family-disability-services', name: 'USAGov: Disability services', url: 'https://www.usa.gov/disability-services' },
];

export const actions = [
  {
    id: 'family-baby-sleep', category: 'family', effort: 'today',
    en: { title: 'Set up a safer place for a baby to sleep', why: 'A clear, firm, flat sleep space lowers the risk of sleep-related infant death.', step: 'Put babies on their backs for every sleep, in their own crib or bassinet with a fitted sheet. Keep pillows, blankets, and toys out.' },
    es: { title: 'Prepara un lugar más seguro para dormir al bebé', why: 'Una superficie firme, plana y despejada reduce el riesgo de muerte relacionada con el sueño.', step: 'Acuesta al bebé boca arriba cada vez que duerma, en su propia cuna o moisés con sábana ajustable. Retira almohadas, cobijas y juguetes.' },
    sources: ['family-safe-sleep'],
  },
  {
    id: 'family-water-watcher', category: 'family', effort: 'today',
    en: { title: 'Name one adult to watch children near water', why: 'Drowning can happen quickly and quietly, even when a child has taken swim lessons.', step: 'At a pool, lake, or bathtub, choose an adult whose only job is close, active supervision; trade off before that adult takes a break.' },
    es: { title: 'Designa a una persona adulta para vigilar cerca del agua', why: 'Un ahogamiento puede ocurrir rápido y sin ruido, aunque el niño haya tomado clases de natación.', step: 'En la piscina, el lago o la bañera, elige a una persona adulta que vigile de cerca y sin distracciones; releven la tarea antes de tomar un descanso.' },
    sources: ['family-water'],
  },
  {
    id: 'family-store-medicine', category: 'family', effort: 'today',
    en: { title: 'Move medicines out of children’s reach', why: 'Young children can get into medicines, vitamins, and supplements in seconds.', step: 'Put them up and away, out of sight, after every use. Ask visitors to secure medicines in their bags too.' },
    es: { title: 'Guarda los medicamentos fuera del alcance de los niños', why: 'Los niños pequeños pueden encontrar medicamentos, vitaminas y suplementos en segundos.', step: 'Después de cada uso, guárdalos en alto y fuera de la vista. Pide a las visitas que aseguren también los medicamentos de sus bolsos.' },
    sources: ['family-medicine-storage'],
  },
  {
    id: 'family-track-milestones', category: 'family', effort: 'week',
    en: { title: 'Share a child development concern early', why: 'Milestone lists help start a conversation; they do not diagnose a child.', step: 'Use CDC’s milestone tool, then tell the child’s clinician about any skill that worries you. Ask about screening or early intervention.' },
    es: { title: 'Habla pronto sobre una duda del desarrollo infantil', why: 'Las listas de hitos ayudan a iniciar una conversación; no dan un diagnóstico.', step: 'Consulta la herramienta de hitos de los CDC y comenta al profesional de salud cualquier habilidad que te preocupe. Pregunta por evaluaciones o intervención temprana.' },
    sources: ['family-milestones'],
  },
  {
    id: 'family-child-checkup-plan', category: 'family', effort: 'week',
    en: { title: 'Prepare for a child’s routine checkup', why: 'A well visit is a chance to discuss growth, school, mood, and prevention before there is a crisis.', step: 'Check when the next visit is due. Bring your questions, vaccine record, and any concerns from other caregivers or teachers.' },
    es: { title: 'Prepárate para el control médico de tu hijo', why: 'La visita de control permite hablar de crecimiento, escuela, estado de ánimo y prevención antes de una crisis.', step: 'Averigua cuándo toca la próxima visita. Lleva tus preguntas, el registro de vacunas y las observaciones de cuidadores o maestros.' },
    sources: ['family-child-checkup'],
  },
  {
    id: 'family-teen-check-in', category: 'family', effort: 'today',
    en: { title: 'Make room for a teen to talk', why: 'A calm, repeated invitation can make it easier to speak about stress, mental health, or substance use.', step: 'Ask an open question while doing something together, listen without judgment, and offer to help find support if they want it.' },
    es: { title: 'Dale espacio a un adolescente para hablar', why: 'Una invitación tranquila y repetida puede facilitar hablar del estrés, la salud mental o el consumo de sustancias.', step: 'Haz una pregunta abierta mientras hacen algo juntos, escucha sin juzgar y ofrécele ayuda para buscar apoyo si lo desea.' },
    sources: ['family-teen-talk'],
  },
  {
    id: 'family-childcare-help', category: 'family', effort: 'week',
    en: { title: 'Check local child care cost help', why: 'States and territories run child care assistance and other programs, with different rules.', step: 'Use Childcare.gov to find your state or territory’s options, then ask the local program about eligibility and openings.' },
    es: { title: 'Consulta ayudas locales para pagar el cuidado infantil', why: 'Los estados y territorios ofrecen programas con distintas reglas.', step: 'Usa Childcare.gov para encontrar opciones donde vives y pregunta al programa local por los requisitos y cupos.' },
    sources: ['family-childcare'],
  },
  {
    id: 'family-head-start-search', category: 'family', effort: 'week',
    en: { title: 'Look for a nearby Head Start program', why: 'Head Start and Early Head Start connect young children and families with early learning and other supports.', step: 'Search by ZIP code in the official center locator. Ask the local program how to apply and whether space is available.' },
    es: { title: 'Busca un programa Head Start cercano', why: 'Head Start y Early Head Start ofrecen aprendizaje temprano y otros apoyos a niños pequeños y sus familias.', step: 'Busca por código postal en el localizador oficial. Pregunta al programa local cómo solicitar ingreso y si hay cupos.' },
    sources: ['family-headstart'],
  },
  {
    id: 'family-wic-check', category: 'family', effort: 'week',
    en: { title: 'Ask a local WIC office about food support', why: 'WIC may offer food, nutrition help, and referrals during pregnancy and early childhood.', step: 'Find your state or local WIC agency and ask how to apply. The agency can explain its current eligibility rules.' },
    es: { title: 'Pregunta a WIC por apoyo alimentario', why: 'WIC puede ofrecer alimentos, orientación nutricional y referencias durante el embarazo y la primera infancia.', step: 'Encuentra la agencia WIC de tu estado o localidad y pregunta cómo solicitar ayuda. Allí te explicarán los requisitos actuales.' },
    sources: ['family-wic'],
  },
  {
    id: 'family-school-evaluation', category: 'family', effort: 'plan',
    en: { title: 'Ask the school about an evaluation', why: 'A student who is struggling may need an evaluation to see whether disability-related support applies.', step: 'Write down your concerns and ask the public school how to request an evaluation. Keep a copy of your request and the response.' },
    es: { title: 'Pregunta a la escuela por una evaluación', why: 'Un estudiante con dificultades podría necesitar una evaluación para saber si corresponde apoyo por discapacidad.', step: 'Anota tus inquietudes y pregunta a la escuela pública cómo solicitar una evaluación. Guarda copia de tu solicitud y la respuesta.' },
    sources: ['family-school-support'],
  },
  {
    id: 'family-fall-hazards', category: 'family', effort: 'today',
    en: { title: 'Clear one fall hazard at home', why: 'Trips at home can cause serious injuries, especially for older adults.', step: 'Walk a usual route with the person who uses it. Remove clutter and loose rugs, improve lighting, and note where a grab bar or rail may help.' },
    es: { title: 'Elimina un peligro de caída en casa', why: 'Los tropiezos en casa pueden causar lesiones graves, sobre todo en personas mayores.', step: 'Recorre con la persona el camino que suele usar. Retira obstáculos y alfombras sueltas, mejora la luz y apunta dónde serviría una barra de apoyo.' },
    sources: ['family-falls'],
  },
  {
    id: 'family-balance-plan', category: 'family', effort: 'week',
    en: { title: 'Add balance and strength to an older adult’s week', why: 'Balance and strength activity can help reduce fall risk.', step: 'Ask a clinician or local senior center about a suitable class or routine, especially after a fall or if walking feels unsteady.' },
    es: { title: 'Incluye ejercicios de equilibrio y fuerza en la semana', why: 'Estas actividades pueden ayudar a reducir el riesgo de caídas en personas mayores.', step: 'Pregunta a un profesional de salud o centro de mayores por una clase o rutina adecuada, especialmente después de una caída o si hay inestabilidad al caminar.' },
    sources: ['family-falls', 'family-older-vision'],
  },
  {
    id: 'family-medicine-list', category: 'family', effort: 'week',
    en: { title: 'Review an older adult’s medicine list', why: 'Some medicines and combinations can cause dizziness or other problems.', step: 'List prescriptions, over-the-counter drugs, and supplements. Bring the list to a pharmacist or clinician and ask about side effects; do not stop a medicine on your own.' },
    es: { title: 'Revisa la lista de medicamentos de una persona mayor', why: 'Algunos medicamentos y combinaciones pueden causar mareos u otros problemas.', step: 'Anota las recetas, los medicamentos sin receta y los suplementos. Lleva la lista a un farmacéutico o profesional de salud y pregunta por efectos secundarios; no suspendas nada por tu cuenta.' },
    sources: ['family-medicine-review'],
  },
  {
    id: 'family-driving-options', category: 'family', effort: 'plan',
    en: { title: 'Plan rides before driving becomes difficult', why: 'Having other ways to get around helps an older adult keep appointments and connections.', step: 'Together, list nearby transit, rides from trusted people, and delivery options. Discuss any driving concerns with a clinician.' },
    es: { title: 'Planea otros traslados antes de que conducir sea difícil', why: 'Tener alternativas ayuda a una persona mayor a mantener sus citas y vínculos.', step: 'Hagan juntos una lista de transporte local, personas de confianza que puedan llevarla y opciones de entrega. Hablen de cualquier inquietud al conducir con un profesional de salud.' },
    sources: ['family-driving'],
  },
  {
    id: 'family-care-wishes-talk', category: 'family', effort: 'plan',
    en: { title: 'Talk about future care wishes', why: 'Loved ones can make better decisions when they know what matters to the person receiving care.', step: 'Ask whom the person trusts to speak for them and what care matters most. Ask a care team about advance directives and your state’s forms.' },
    es: { title: 'Hablen de las preferencias de atención futura', why: 'La familia puede decidir mejor cuando conoce lo que le importa a la persona que recibe atención.', step: 'Pregunta en quién confía para hablar en su nombre y qué cuidados valora más. Consulta al equipo médico sobre las instrucciones anticipadas y los formularios de tu estado.' },
    sources: ['family-care-wishes'],
  },
  {
    id: 'family-care-notebook', category: 'family', effort: 'today',
    en: { title: 'Start one shared care record', why: 'A clear record makes handoffs and appointments easier for a caregiving team.', step: 'With the person’s permission, keep contacts, medicines, appointments, and questions in one place that the right helpers can access.' },
    es: { title: 'Empieza un registro compartido de cuidados', why: 'Un registro claro facilita los relevos y las citas del equipo cuidador.', step: 'Con permiso de la persona, reúne contactos, medicamentos, citas y preguntas en un lugar accesible para quienes deban ayudar.' },
    sources: ['family-care-notebook'],
  },
  {
    id: 'family-share-tasks', category: 'family', effort: 'week',
    en: { title: 'Split caregiving into specific tasks', why: 'One person does not have to handle every ride, meal, call, and form.', step: 'Ask the person receiving care what help they want. Write a short task list and invite trusted people to take one recurring job each.' },
    es: { title: 'Reparte tareas concretas de cuidado', why: 'Una sola persona no tiene que encargarse de cada traslado, comida, llamada y trámite.', step: 'Pregunta a quien recibe cuidados qué ayuda desea. Haz una lista breve e invita a personas de confianza a asumir una tarea habitual cada una.' },
    sources: ['family-care-team'],
  },
  {
    id: 'family-respite-search', category: 'family', effort: 'plan',
    en: { title: 'Plan a caregiver break', why: 'Respite care can give a regular caregiver time to rest or handle other needs.', step: 'Ask local aging or disability services about in-home, day, or short-stay respite. Check availability, cost, and fit before booking.' },
    es: { title: 'Planea un descanso para quien cuida', why: 'El cuidado de relevo puede dar tiempo para descansar o atender otras necesidades.', step: 'Pregunta a los servicios locales para personas mayores o con discapacidad por opciones en casa, de día o por estancias cortas. Confirma disponibilidad, costo y adecuación antes de reservar.' },
    sources: ['family-respite'],
  },
  {
    id: 'family-eldercare-locator', category: 'family', effort: 'week',
    en: { title: 'Find local aging services', why: 'Nearby programs may help with meals, transportation, home support, or caregiver needs.', step: 'Search the Eldercare Locator by ZIP code or call its information line, then ask which local services fit your situation.' },
    es: { title: 'Encuentra servicios locales para personas mayores', why: 'Algunos programas cercanos pueden ayudar con comidas, transporte, apoyo en casa o necesidades de cuidadores.', step: 'Busca por código postal en Eldercare Locator o llama a su línea de información; pregunta qué servicios se ajustan a tu situación.' },
    sources: ['family-eldercare'],
  },
  {
    id: 'family-caregiver-check', category: 'family', effort: 'today',
    en: { title: 'Check in on the caregiver too', why: 'Caregiving can strain sleep, health, and relationships over time.', step: 'Ask a caregiver what would lighten this week. Offer one specific errand, meal, ride, or hour of relief they can accept or decline.' },
    es: { title: 'Pregunta también cómo está quien cuida', why: 'Con el tiempo, cuidar puede afectar el sueño, la salud y las relaciones.', step: 'Pregunta qué aliviaría esta semana. Ofrece una compra, una comida, un traslado o una hora de descanso concretos, que pueda aceptar o rechazar.' },
    sources: ['family-caregiver-health'],
  },
  {
    id: 'family-accessible-communication', category: 'family', effort: 'week',
    en: { title: 'Ask for disability communication access', why: 'People with hearing, vision, or speech disabilities may need aids to take part in care or public services.', step: 'When scheduling, explain which aid you need, such as a qualified sign-language interpreter, captions, or an accessible document. Ask how it will be provided.' },
    es: { title: 'Solicita apoyos de comunicación por discapacidad', why: 'Las personas con discapacidad auditiva, visual o del habla pueden necesitar apoyos para participar en citas o servicios.', step: 'Al programar la cita, explica qué apoyo necesitas, como un intérprete de lengua de señas calificado, subtítulos o documentos accesibles. Pregunta cómo se proporcionará.' },
    sources: ['family-communication'],
  },
  {
    id: 'family-accessible-rides', category: 'family', effort: 'plan',
    en: { title: 'Ask about accessible transit options', why: 'A disability can make standard bus or rail service hard to use for some trips.', step: 'Contact your local transit agency about accessible routes and ADA paratransit. Ask how its eligibility process works; a diagnosis alone does not decide it.' },
    es: { title: 'Pregunta por transporte accesible', why: 'Para algunas personas con discapacidad puede ser difícil usar autobuses o trenes en ciertos trayectos.', step: 'Consulta a la agencia local por rutas accesibles y paratránsito de la ADA. Pregunta cómo determinan si cumples los requisitos; un diagnóstico por sí solo no lo determina.' },
    sources: ['family-transit'],
  },
  {
    id: 'family-disability-emergency', category: 'family', effort: 'plan',
    en: { title: 'Plan for disability needs in an emergency', why: 'A power outage or evacuation can interrupt equipment, medicines, and daily support.', step: 'With the person involved, list essential supplies, helpers, accessible transport, and backup power needs. Share the plan with trusted people.' },
    es: { title: 'Planea las necesidades de discapacidad ante emergencias', why: 'Un apagón o una evacuación puede interrumpir equipos, medicamentos y apoyos diarios.', step: 'Con la participación de la persona, anota suministros esenciales, personas de apoyo, transporte accesible y necesidades de energía de respaldo. Comparte el plan con personas de confianza.' },
    sources: ['family-disability-ready'],
  },
  {
    id: 'family-disability-services-search', category: 'family', effort: 'week',
    en: { title: 'Explore disability services by need', why: 'Support may involve health care, transportation, work, school, or financial programs.', step: 'Use USAGov’s disability directory to choose the need that matters now, then check the program’s own application rules.' },
    es: { title: 'Busca servicios de discapacidad según tu necesidad', why: 'El apoyo puede incluir atención médica, transporte, trabajo, escuela o programas económicos.', step: 'En el directorio de USAGov, elige la necesidad más urgente y después revisa las reglas de solicitud del programa correspondiente.' },
    sources: ['family-disability-services'],
  },
];
